### ISSUE TITLE
Example repo?

### ISSUE THREAD

**Issue by mayel** [elixir-capsule/capsule#10]
Hello, capsule looks great and we're looking to adopt it in our open-source project.
Any chance you could share an example repo using capsule + capsule_ecto + capsule_supplement? This would go a long way to help with adoption given the minimal docs ;)

**Comment by tfwright** [comment]
Sure I'll look into this

**Comment by mayel** [comment]
Cheers, I've gone ahead and started the integration by just looking at the code :) I'm sure it can be useful to others or to double check things though!
Will have a couple more significant PRs coming in soon as well.

**Comment by tfwright** [comment]
Thought about this, even started building out a repo, but I realized I had no idea what to add that is not already in tests for the various libraries. Can you explain a bit more what you expect to see in this kind of demo?
